AWSTemplateFormatVersion: "2010-09-09"
Description: Ithemba - data (DynamoDB, RDS, S3 buckets)
Resources:
  ServicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ithemba-services
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: province
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: province
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
  InsightsBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnet group for RDS
      SubnetIds:
        - !ImportValue private-subnet-id
Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref ServicesTable
    Export:
      Name: ithemba-services-table-name
  InsightsBucketName:
    Description: Name of the S3 bucket for insights data
    Value: !Ref InsightsBucket
  DeploymentBucketName:
    Description: Name of the deployment bucket name
    Value: !Ref DeploymentBucket
    Export:
      Name: ithemba-services-deployment-name