AWSTemplateFormatVersion: "2010-09-09"
Description: Ithemba - application (Lambda, API Gateway, CloudFront, EC2)
Resources: 
  DirectoryFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ithemba-directory-api
      Runtime: python3.13
      Handler: handler.lambda_handler
      Role: arn:aws:iam::022860393089:role/LabRole
      Code:
        S3Bucket: !ImportValue ithemba-services-deployment-name
        S3Key: lambda.zip
      Environment:
        Variables:
          TABLE_NAME: !ImportValue ithemba-services-table-name
